const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const storage=new Map();
const sandbox={window:{},document:{addEventListener(){}},console,Date,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)}};
vm.createContext(sandbox);
for(const file of ['achievements-data.js','achievements.js','state.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../js',file),'utf8'),sandbox);
const api=sandbox.window.MuseumAchievements,states=sandbox.window.MuseumState;
assert.equal(sandbox.window.MuseumAchievementDefinitions.length,0,'Production catalog must remain empty.');
assert(api.register({id:'test-progress',name:'仅测试',target:3}));
assert(api.register({id:'test-hidden',name:'仅测试隐藏',hidden:true}));
assert(!api.register({id:'test-progress',name:'重复'}));
assert(!api.register({id:'invalid',name:'无效',target:0}));
let state=states.create({id:'a',username:'test'}),writes=0;
const options={notify:false,save:()=>{writes++;states.save(state,'a');}};
assert(!api.unlock(state,'undefined-id',options));assert.equal(writes,0);
assert(api.increment(state,'test-progress',1,options));assert.equal(api.status(state,'test-progress').progress,1);
assert(!api.setProgress(state,'test-progress',0,options));assert(!api.increment(state,'test-progress',-1,options));assert(!api.setProgress(state,'test-progress',NaN,options));assert.equal(writes,1);
states.saveSlot(state,'a',0);
assert(api.increment(state,'test-progress',9,options));assert.equal(api.status(state,'test-progress').progress,3);assert(api.status(state,'test-progress').unlockedAt);
const earnedAt=api.status(state,'test-progress').unlockedAt;
assert(!api.unlock(state,'test-progress',options));assert(!api.increment(state,'test-progress',1,options));assert.equal(writes,2);assert.equal(api.status(state,'test-progress').unlockedAt,earnedAt);
state=states.load('a');assert(api.status(state,'test-progress').unlocked);assert.equal(api.status(state,'test-progress').unlockedAt,earnedAt);
const before=states.loadSlot('a',0);assert(!api.status(before,'test-progress').unlocked);assert.equal(api.status(before,'test-progress').progress,1);
const other=states.create({id:'b',username:'other'});states.save(other,'b');assert.equal(states.load('b').achievements.length,0);
const legacy=states.create({id:'legacy'});legacy.achievements=['old-id','old-id',null];delete legacy.achievementRecords;states.save(legacy,'legacy');const recovered=states.load('legacy');assert.equal(recovered.achievements.join(','),'old-id');assert.deepEqual(Object.keys(recovered.achievementRecords),[]);
assert.equal(api.status(recovered,'old-id'),null,'Removed definitions stay stored but do not show as current achievements.');
console.log('PASS: empty production registry, validation, progress, one-time unlock, timestamps, autosave/slot rollback, account isolation and legacy recovery.');
